## 1. Массивы в NumPy


---



In [1]:
import numpy as np

In [3]:
mylist = [1, 2, 3]
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
len(np.linspace(0, 5, 21))

21

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(1)

array([0.1444367])

In [29]:
np.random.rand(5, 6)

array([[0.73350128, 0.60142919, 0.94499544, 0.86375417, 0.92502047,
        0.10358784],
       [0.55157648, 0.79969594, 0.3587094 , 0.52933023, 0.20706463,
        0.2059028 ],
       [0.41160991, 0.52876723, 0.81047846, 0.08300946, 0.27867015,
        0.54065363],
       [0.1120252 , 0.70751631, 0.75393901, 0.70726753, 0.11083262,
        0.30615128],
       [0.6458825 , 0.37282062, 0.73246607, 0.43012996, 0.80012209,
        0.29676112]])

In [30]:
np.random.randn(10)

array([-1.05143534, -0.55603059, -1.52791599, -1.10440604, -0.20132455,
       -0.22179984, -0.01092647,  0.38222166, -0.3122712 ,  0.22196755])

In [31]:
np.random.randn(2, 3)

array([[-0.51770235,  0.26750469, -0.50156464],
       [ 0.66254241, -0.502275  ,  1.09591774]])

In [33]:
np.random.randint(0, 101, (4, 5))

array([[17, 57, 82, 54, 19],
       [25, 97, 32,  4, 35],
       [39, 32, 66, 12, 31],
       [43, 97, 50, 77, 10]])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [66]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
arr.shape

(100,)

In [46]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [57]:
ranarr.max(), ranarr.min(), ranarr.argmax(), ranarr.argmin()

(99, 2, 5, 7)

In [59]:
ranarr.dtype

dtype('int64')

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
arr = arr.reshape(10, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
arr.shape

(10, 10)



---
## Индексация по выбору


---




In [69]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr[8]

8

In [71]:
arr[1:5]

array([1, 2, 3, 4])

In [73]:
arr[:5]

array([ 5,  6,  7,  8,  9, 10])

In [74]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [78]:
arr = np.arange(0, 11)

In [80]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [84]:
arr_copy = arr.copy()

In [85]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [86]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [88]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d.shape

(3, 3)

In [90]:
arr_2d[0]

array([ 5, 10, 15])

In [91]:
arr_2d[1][1]

25

In [92]:
arr_2d[0, 2]

15

In [93]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [97]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [99]:
bool_array = arr > 4
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [101]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])



---
## Операции NumPy


---





In [103]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [106]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [107]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [108]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [109]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
arr / arr

<ipython-input-110-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
1 / arr

<ipython-input-111-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [112]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [113]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [114]:
np.log(arr)

<ipython-input-114-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [115]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
arr.sum()

45

In [117]:
arr.mean()

4.5

In [118]:
arr.max()

9

In [119]:
arr.min()

0

In [122]:
arr.var() #Дисперсия

8.25

In [123]:
arr.std() #Среднее квадратичное отклонение

2.8722813232690143

In [125]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [126]:
arr_2d.shape

(5, 5)

In [127]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
arr_2d.sum()

300

In [130]:
arr_2d.sum(axis=0) #сумма колонок

array([50, 55, 60, 65, 70])

In [132]:
arr_2d.sum(axis=1) #сумма строк

array([ 10,  35,  60,  85, 110])